# ---------- List of plugins ------------xa
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'laktak/extrakto'

set -g @plugin 'christoomey/vim-tmux-navigator'

#set -g @plugin 'vaaleyard/tmux-dotbar'
#set -g @tmux-dotbar-right true
#set -g @tmux-dotbar-position top

# ----- powerbar and colorscheme
set -g @plugin 'fabioluciano/tmux-powerkit'

# Basic configuration
set -g @powerkit_plugins "datetime,battery,nowplaying"
set -g @powerkit_theme "monokai"
set -g @powerkit_theme_variant "dark"


# ------- stuff for integration with alacritty
# Allow tmux to send 24-bit color to the terminal
# (The 'a' flag appends to the option, avoiding overwrites)
set -ag terminal-overrides ",xterm-256color:RGB"
set -ag terminal-overrides ",alacritty:RGB"

# -----  setting settigs ------------

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# start counting at 1 :)
set-option -g base-index 1                # window index will start with 1
set-window-option -g pane-base-index 1    # pane index will start with 1
set-option -g renumber-windows on


# Enable mouse control (clickable windows, panes, resizable panes)
set -g mouse on

# Disables auto rename
set-option -g allow-rename off

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
